```{=html}
<style>
body{text-align: justify}
</style>
```



:::: progress
::: {.progress-bar style="width: 100%;"}
:::
::::

# Apresentação {.unnumbered}

O presente e-book tem como propósito organizar, num formato didático e acessível, as informações teóricas e práticas sobre a aplicação da Metodologia da Transitividade no contexto do Ensino Médio. Esta produto é fruto da sistematização de práticas pedagógicas que buscam aproximar a escola da realidade dos estudantes, promovendo uma educação pautada no diálogo, na reflexão crítica e na práxis.

A proposta aqui delineada adapta os passos descrito no projeto sobre a referida metodologia, transpondo-os para a prática pedagógica escolar: a produção de pequenos vídeos documentais que possam ser utilizados de forma educativa nas redes sociais (como Reels, TikTok e Shorts). O objetivo não é o domínio técnico de produção audiovisual ou mero entretenimento, mas visa utilizar o celular como um instrumento de investigação social e de leitura crítica do mundo.

:::: progress
::: {.progress-bar style="width: 100%;"}
:::
::::

